### ISSUE TITLE
404's list

### ISSUE THREAD

**Issue by stavares843** [breck7/scroll#100]
Status | URL | Source link text
-- | -- | --
400 Bad Request | https://developers.facebook.com/tools/debug | [Facebook](https://scroll.pub/)
404 Not Found | https://scroll.pub/public/blog/url | [linktext](https://scroll.pub/public/blog/indented-heredocs.html)
404 Not Found | https://scroll.pub/demo/?text= | [clear everything](https://scroll.pub/public/blog/indented-heredocs.html)
404 Not Found | https://scroll.pub/potato.html | [a relative link](https://scroll.pub/releaseNotes.html)
400 Bad Request | https://$2/ | [$1](https://scroll.pub/releaseNotes.html)
404 Not Found | https://example.com/report | [This report](https://scroll.pub/releaseNotes.html)
404 Not Found | https://scroll.pub/public/blog/imageurl |[img/src](https://scroll.pub/public/blog/indented-heredocs.html)
-1 Not found: The server name or address could not be resolved | http://www.youtube/ | [www.youtube](https://scroll.pub/releaseNotes.html)

**Comment by breck7** [comment]
https://developers.facebook.com/tools/debug works for me

**Comment by breck7** [comment]
Going to close this one. The only one I think is meant to be clicked on is the first one. Not too concerned if robots click on a link that's more of a demo :) (i.e. example.com).
