### ISSUE TITLE
Please apply CC0 public domain dedication for this repository

### ISSUE THREAD

**Issue by penyuan** [breck7/scroll#106]
Hello @breck7, 

First of all, I love the concept of Scroll. Amazing work and thank you for sharing it with the world! ❤️

I see in issues such as #58 or #87, and in [this one](https://github.com/breck7/pldb/issues/48#issuecomment-1230696016) for pldb that **you said**: 

> ...that's intentional.... It's all public domain.

and: 

> I don't believe in licenses. I believe (c)opyright is anti-property rights (I support actual property rights), and Imaginary Property rights should be abolished from the face of the earth, because they are euphemisms for (c)ensorship and Intellectual Slavery.

I agree with your sentiment and desire for Scroll and your other great works to be in the public domain, without copyright restrictions. Thank you for doing this, and I wish more people shared your views.

There is one frustrating snag, however, which is that according to existing laws and the [Berne Convention](https://en.wikipedia.org/wiki/Berne_Convention), copyright restricts all creative works ***automatically*** as soon as they are created, including this repository whether we like it or not. I don't like this, but it is the reality we live in.

What this means is that, absent additional action from you, this repository is actually closed source by default! It is literally a severe criminal offense for other people to copy and reuse the code (with very limited and fuzzy fair use/fair dealing exceptions). This has the unintentional effect of preventing others from making use of and learning from your amazing work, which is a real shame. For most people, when they see this repository, they will assume it is closed source, which cuts off a huge potential audience of your work. Again, this is a huge shame because Scroll is wonderful and more people should see it.

Fortunately, **this is very easy to solve by applying the [CC0 public domain dedication](https://creativecommons.org/publicdomain/zero/1.0/) to this repository**. As [described on choosealicense.com](https://choosealicense.com/licenses/cc0-1.0/): 

> [CC0] waives copyright interest in a work you've created and dedicates it to the world-wide public domain. *Use CC0 to opt out of copyright entirely*... (emphasise mine)

Since you clearly stated that you want to opt out of copyright, the CC0 public domain dedication is a perfect fit.

All you have to do is: 

1. Add a small section to the README stating that everything in this repository is released under CC0, i.e. no copyright applies.
2. Add a `LICENSE` file with the contents of CC0. To be clear, the filename is "LICENSE", but that is just the standard way to do things, and its contents could be CC0 which waives copyright.

That's it!

By applying CC0 to this repository, you would: 

* Formally make it clear that you don't want copyright to restrict your work.
* Make this intent machine-readable (via the `LICENSE` file and GitHub metadata), which greatly increases discoverability and ease of adoption by others.
* Promote a world where creativity is not limited by copyright.

If helpful, I'm happy to send a pull request with these updates.

Thank you again for creating Scroll and your desire to share it without copyright restrictions. CC0 will bring that vision to reality.

P.S. The same applies to all of your other repositories.

**Comment by breck7** [comment]
Hi @penyuan!

I'm open to considering this argument.

Besides this, are there any other things that we could improve to make Scroll better serve you?

Thanks!
-Breck

**Comment by celtic-coder** [comment]
Hi @penyuan, back in Sept / Oct, I mentioned the [PDDL license](https://github.com/breck7/pldb/discussions/125) which is specifically for public domain databases. Might you have any thoughts on the use of this license?

Kind Regards,
Liam

**Comment by breck7** [comment]
No response from @penyuan so closing this one.

**Comment by penyuan** [comment]
Please see continuing discussions here: 
https://github.com/breck7/pldb/issues/503
