### ISSUE TITLE
Custom markup symbols (bold/italic) instead of the defaults

### ISSUE THREAD

**Issue by eugenesvk** [breck7/scroll#122]
Is Scroll flexible enough to allow Parsers to be extended to replace the default markup symbols?

For example, I'd like the asterisk to just be an actual asterisk and use something else for bold

Or make the underline used for underlining text and something else for italics?

**Comment by breck7** [comment]
> I'd like the asterisk to just be an actual asterisk 

Yes, but the documentation for that is not good yet.

Demo:

http://hub.scroll.pub/edit.html?folderName=asteriskdemo&fileName=index.scroll&password=homeamsomefindnewsnew

> use something else for bold...Or make the underline used for underlining text and something else for italics?

Yes, the aftertext directives can be added/expanded easily. *In theory*. In practice that code is a bit messy and it's on my todo list to clean it up. But you can absolutely bank on it that this is not only possible but is possible and will be very easy in later versions.

**Comment by eugenesvk** [comment]
The demo is for overriding asterisks as a prefix, but I only meant asterisks as used in the `*bold*` paired markup

> will be very easy in later versions.

So that could be a "global" override  instead of being used for every piece of text (as far as I understand from https://breckyunits.com/aftertext.html)?

Similarly to how your demo allows a global override of the asterisk as a prefix

**Comment by breck7** [comment]
>  but I only meant asterisks as used in the *bold* paired markup

Oh that makes sense. Sorry I read it wrong.

The relevant line of source code is https://github.com/breck7/scroll/blob/e20dc4a0ddb87db82eb377e8c5967f7297bc3f2e/parsers/aftertext.parsers#L216

I can clean this code up soon to make it easier to accomplish what you want. Good idea!

**Comment by eugenesvk** [comment]
Would be nice indeed if all one had to do was something like "substitute wrapsOnParser" and just change this one `const wraps` with custom delimiters, while leaving all existing rules as is (and when you update the inner rules this custom substitution would benefit from that as well), and it would work everywhere `wrapsOnParser` is used in the current parsers

For example, I see that here is `wrapParser` that `extends wrapsOnParser`, guess it should continue to work? Or maybe this could lead to issues with priorities? For example, this `wrapParser` as far as I understand defines `_` as an italic marker, but in my example I've replaced wrapsOnParser to use `_` as an underline marker, so which parser would win?

**Comment by breck7** [comment]
Okay. I added a `inlineMarkups` parser. Would love to hear what you think @eugenesvk 

https://try.scroll.pub/#scroll%0A%20thinColumns%201%0A%20%0A%20gazetteCss%0A%20%0A%20%23%20Custom%20Inline%20Markups%20Test%0A%20%0A%20belowAsCode%203%0A%20inlineMarkups%0A%20%20*%0A%20%20%20%2F%2F%20disable%20bold%0A%20%20_%20u%0A%20%20%20%2F%2F%20override%20underline%0A%20%20~~~%20marquee%0A%20%20%20%2F%2F%20Add%20marquee!%0A%20%0A%20*This*%20should%20not%20be%20bold.%20~~~This%20should%20be%20a%20marquee.~~~%20And%20_this_%20should%20be%20underlined.%0A%20%0A%20

**Comment by eugenesvk** [comment]
Looks great, and even nested markup works, [playground example](https://try.scroll.pub/#scroll%0A%20thinColumns%201%0A%20gazetteCss%0A%20inlineMarkups%0A%20%20*%0A%20%20%20%2F%2F%20Bold%3A%20%E2%86%91dis%2Fen-able%E2%86%93%0A%20%20%F0%9F%85%91%20b%0A%20%20%E2%93%91%20b%0A%20%20%E2%92%B7%20b%0A%20%20%F0%9F%9E%B1%20b%0A%20%20%E2%97%BE%20b%0A%20%20%20%2F%2F%20Italic%3A%20enable%E2%86%93%0A%20%20%2F%20i%0A%20%20%E2%A7%B8%20em%0A%20%20%20%2F%2F%20Strikethrough%3A%20enable%E2%86%93%0A%20%20%E2%8E%AF%20strike%0A%20%20%20%2F%2F%20Underline%3A%20override_%20(was%20italic)%2C%20enable%E2%86%93%0A%20%20_%20u%0A%20%20%E2%8E%BD%20u%0A%20%20%20%2F%2F%20Fixed-width%2Fcode%3A%20enable%E2%86%93%0A%20%20%E2%AD%A4%20code%0A%20%20%E2%A5%8A%20code%0A%20%20%20%2F%2F%20Smallcaps%3A%20enable%E2%86%93%20(don't%20work)%0A%20%20%EA%9C%9B%20small%0A%20%20%CB%B0%20sc%0A%20%0A%20*Not%20bold*%20_underline%E2%86%92___%E2%86%90not%20italic_%0A%20%60how%20to%20escape%3F%60%60%60properly%20marker%60%20the%20marker%20isn't%20marked%20as%20code%2C%20so%20triple%20marker%20isn't%20a%20proper%20escape%3F%0A%20%0A%20%E2%97%BEbold%20black%E2%97%BE%E2%97%BE%E2%97%BEmedium-small%20square.%E2%97%BE%20or%0A%20%F0%9F%9E%B1bold%F0%9F%9E%B1%F0%9F%9E%B1%F0%9F%9E%B1asterisk.%F0%9F%9E%B1%20%F0%9F%85%91or%F0%9F%85%91%F0%9F%85%91%F0%9F%85%91.%F0%9F%85%91%20%E2%93%91or%E2%93%91%E2%93%91%E2%93%91.%E2%93%91%20%E2%92%B7or%E2%92%B7%E2%92%B7%E2%92%B7.%E2%92%B7%0A%20%2Fitalic%2F%2F%2Fslash.%2F%20%20or%20%E2%A7%B8big%E2%A7%B8%E2%A7%B8%E2%A7%B8solidus.%E2%A7%B8%0A%20%E2%8E%BDhorizontal%E2%8E%BD%E2%8E%BD%E2%8E%BDscan%20line-9%E2%8E%BD%0A%20%CB%B0smallcaps%20with%CB%B0%CB%B0%CB%B0%20marker%CB%B0%20%EA%9C%9Bor%EA%9C%9B%EA%9C%9B%EA%9C%9B.%EA%9C%9B%20%0A%20%E2%AD%A4left%20right%E2%AD%A4%E2%AD%A4%E2%AD%A4%20triangle-headed%20arrowr%E2%AD%A4%20%E2%A5%8Aor%E2%A5%8A%E2%A5%8A%E2%A5%8A.%E2%A5%8A%0A%20%E2%8E%AFstrikethrough%20with%20%E2%8E%AF%E2%8E%AF%E2%8E%AF%20marker%E2%8E%AF%3A%20horizontal%20line%20extension%0A%20%2F_%E2%97%BEnested%20b%26it%26und%E2%97%BE%20it%26und%2F%20%E2%97%BEb%26und%E2%97%BE_%0A%20)! Though for some reason `/a//b/` instead of to italics prints a/<>b, couldn't find the reason and how escaping works

(triple symbol works, but isn't a proper escape since
```
`a```b`
```
while printing
```
a`b
```
doesn't surround the actual backtick in "code" highlight?
So how would you escape the default or custom marker?

**Comment by breck7** [comment]
> Looks great, and even nested markup works

Great to hear!

> (triple symbol works, but isn't a proper escape since
> So how would you escape the default or custom marker?

I've found I rarely need escapes, and in those cases I just use a `code` parser or disable the conflicting markups, or use a raw html div `<div>`. Seems to work great, and keeps things simple for most cases.

If one needed escapes a lot, I'd probably suggest building one's own paragraph parser perhaps.

**Comment by breck7** [comment]
One more feature: added support for attributes.

https://try.scroll.pub/#scroll%0A%20gazetteCss%0A%20%0A%20Custom%20markups%20now%20accept%20attributes.%0A%20%0A%20inlineMarkups%0A%20%20%2F%2F%20delimiter%20tag%20%5Battributes%5D%0A%20%20%40%20button%20class%3D%22button%22%0A%20%0A%20Make%20this%20a%20%40button%40%0A%20%0A%20css%0A%20%20.button%20%7B%0A%20%20background-color%3A%20%234CAF50%3B%0A%20%20border%3A%20none%3B%0A%20%20color%3A%20white%3B%0A%20%20padding%3A%205px%2010px%3B%0A%20%20text-align%3A%20center%3B%0A%20%20cursor%3A%20pointer%3B%0A%20%20border-radius%3A%2012px%3B%0A%20%20%7D%0A%20
