### ISSUE TITLE
CSS integrations (MIT)

### ISSUE THREAD

**Issue by bukit-kronik** [breck7/scroll#147]
Just a friendly suggestion to integrate/create Scroll themes with PicoCSS and or Shoelace.

https://picocss.com (fast)

https://shoelace.style (rich features)

**Comment by breck7** [comment]
@bukit-kronik this is fantastic!

Here's what I've done so far: https://pico.scroll.pub/

Are you involved with pico? Perhaps we can make up a beautiful Pico + Scroll demo page and offer pico users one click to clone and deploy on scrollhub.
