### ISSUE TITLE
permission and redirect issue

### ISSUE THREAD

**Issue by bardicreels** [breck7/scroll#151]
v161.0.4

restart with "pm2 restart server" command resets permissions for the subfolder/subdomain and forwards to scrollhub starting template instead of index.html for that subdomain

thought it was an update script on my end but this is on a refreshed droplet and updated scroll version

fix: deleting the folder and re-scp'ing it to remote

**Comment by breck7** [comment]
Thanks for the report! Investigating now

**Comment by breck7** [comment]
Okay, do you know which v of ScrollHub you were on before? I had a bad release note message for `📦 0.36.0 11/17/2024`, which may be the culprit. Updated it below:

```
⚠️ BREAKING: by default ScrollHub server now serves `~` folder, not `~/folders`. You can update your pm2 job to launch ScrollHub from `~/folders` or move folders from `~/folders` to `~`
```

**Comment by bardicreels** [comment]
I believe it was 140. 

after the refresh and install for 161, no folder directory was created at all for some reason. 
I thought this might be intentional so that new hubs are created at root ?

i should have posted this in ScrollHub repo, srry

**Comment by breck7** [comment]
> no folder directory was created at all 
> I thought this might be intentional so that new hubs are created at root ?

Yup! That is the new design. ScrollHub now takes a parameter of which root folder to serve. (the default being "~").

This makes it easier to use locally. I just type "hub" at the command line in any folder on my machine, and ScrollHub launches and starts serving that folder.
