### ISSUE TITLE
Add above/belowAsHtmlParser?

### ISSUE THREAD

**Issue by btheado** [breck7/scroll#153]
Parsers to display the html output would be a nice complement to the above/belowAsCode parsers.

Here is an implementation I made:

```
belowAsHtmlParser
 extends belowAsCodeParser
 description displays html output of next particle in a code block
 cueFromId
 javascript
  get code() {
   return this.selectedParticles.filter(p => p.buildHtml).map(p => p.buildHtml()).join("\n")
  }
```

Does it make sense to include something like the above native to scroll?

I'm using the above parser to demonstrate a few other parsers I implemented at https://hub.scroll.pub/codeplaygrounds/index.html

**Comment by breck7** [comment]
Oh this looks like it could be super helpful for both Scroll development and for teaching Scroll. I've already spotted a few places we could make the output HTML better.

I think it makes sense to add it to the standard library. Also an "aboveAsHtml" as well?

Probably should add it to either "scroll/parsers/documentation.parsers"  or "scroll/parsers/debug.parsers".

Here it is in the try console:

https://try.scroll.pub/#scroll%0A%20theme%20gazette%0A%20%0A%20belowAsHtmlParser%0A%20%20extends%20belowAsCodeParser%0A%20%20description%20displays%20html%20output%20of%20next%20particle%20in%20a%20code%20block%0A%20%20cueFromId%0A%20%20javascript%0A%20%20%20get%20code()%20%7B%0A%20%20%20%20return%20this.selectedParticles.filter(p%20%3D%3E%20p.buildHtml).map(p%20%3D%3E%20p.buildHtml()).join(%22%5Cn%22)%0A%20%20%20%7D%0A%20%0A%20belowAsHtml%0A%20%23%20Hello%20world%0A%20%0A%20copyButtons%0A%20belowAsHtml%0A%20iris%0A%20%20where%20petal_length%20%3D%204.2%0A%20%20%20printTable%0A%20%20%0A%20%20

**Comment by btheado** [comment]
> Also an "aboveAsHtml" as well?

Yes, I agree

> Probably should add it to either "scroll/parsers/documentation.parsers" or "scroll/parsers/debug.parsers".

I can make a PR for it. Adding them to the documentation.parsers file makes the most sense to me.

**Comment by breck7** [comment]
Great, I'll merge when you send the PR.
