### ISSUE TITLE
MaxColumns 1 doesn't work on index page

### ISSUE THREAD

**Issue by alexjj** [breck7/scroll#46]
Adding `maxColumns 2` to `scroll.settings` works fine but when I move to 1 it doesn't. I know this defeats the style purpose of the site but I was curious to see what it looked like.

**Comment by breck7** [comment]
Yes that is correct. `maxColumns` is not used in the rendering of the index page. It is only used when compiling the html for the single article pages. This could be addressed when/if refactoring the list pages like the index (https://github.com/publicdomaincompany/scroll/issues/41).

**Comment by breck7** [comment]
The concept of `scroll.settings` has been removed, now everything just goes in a scroll file, including things like `maxColumns`. Currently only the single page template uses that setting, group pages do not.
