### ISSUE TITLE
Examples of custom header/footer

### ISSUE THREAD

**Issue by alexjj** [breck7/scroll#47]
Can you share an example of this? Am I meant to write the custom content in HTML, do I write that all in the settings file or can it reference another file? 

I tried just plain text e.g. `footer This is a new footer` However, all it did was remove the stock footer. There's no HTML or anything in its place.

![image](https://user-images.githubusercontent.com/440939/149842065-6cb80c76-11f3-43ad-96a4-a09ad473a2da.png)

**Comment by breck7** [comment]
Argh, custom headers and footers are an underdeveloped feature.

Here is an example:
https://github.com/breck7/customHeaderAndFooter

They currently use Stump for HTML (https://jtree.treenotation.org/designer/#standard%20stump) and Hakon (https://jtree.treenotation.org/designer/#standard%20hakon). However, those are both underdeveloped and there's no good reason to require those. I should probably make this template language agnostic. Let me look into that.

**Comment by breck7** [comment]
This has been updated and simplified a lot. Still a lot to do to improve templates et cetera, but for now there are a number of examples now out there including the `readme.scroll` file, which drops the top header and just puts the GitHub logo in the top right:

```
scrollHeader
 div
  class scrollTopRightBarComponent
  div
   class scrollSocialMediaIconsComponent
   a <svg role="img" viewBox="0 0 24 24" xmlns="[http://www.w3.org/2000/svg"><title>GitHub](http://www.w3.org/2000/svg%22%3E%3Ctitle%3EGitHub) icon</title><path d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"/></svg>
    href https://github.com/breck7/scroll
```
