### ISSUE TITLE
scroll-cli: Errors on Windows

### ISSUE THREAD

**Issue by celtic-coder** [breck7/scroll#50]
Hi Breck (@breck7),

On my Windows 10 machine, I created a `C:\Scroll` folder for testing **scroll-cli**. I ran the commands as suggested by `scroll help` on the https://scroll.pub/ page and then by the contents of the [scroll.js](https://github.com/breck7/scroll/blob/main/scroll.js) file.

### scroll init

I ran the `scroll init` command to create these two files:

 - scroll.settings
 - readme.scroll

![scroll-init-output](https://user-images.githubusercontent.com/11787866/180302439-c59b6310-d9ac-4e89-a96f-d1e74d863d63.png)

I am not familiar with JavaScript / TypeScript, but it looks like the **cwd** value in the [initCommand (line 817 to 825)](https://github.com/breck7/scroll/blob/12d21f9120d702c70e31a4566db0542cca175b52/scroll.js#L817-L825) is being resolved correctly to `C:\Scroll`, first in the double quotes (Initializing scroll in...), and then in the single quotes (Initialized new scroll in...) lines.

The **scroll.settings** file has the expected content:

![scroll-settings-content](https://user-images.githubusercontent.com/11787866/180303091-98b880e4-a36d-4038-aa52-a8da234c6a64.png)

as does the **readme.scroll** file:

![readme-scroll](https://user-images.githubusercontent.com/11787866/180327899-333b0a0f-05fe-43c9-92e8-f535bab4a2a5.png)

### scroll build

However, the `scroll build` command fails with this error:

![scroll-build-error-output](https://user-images.githubusercontent.com/11787866/180301148-20e9c212-919c-407c-a66c-043da97801a3.png)

The system is using `Node.js v18.6.0`.

It seems the `const folder = new ScrollFolder(resolvePath(cwd))` in [buildCommand (lines 849 to 854)](https://github.com/breck7/scroll/blob/12d21f9120d702c70e31a4566db0542cca175b52/scroll.js#L849-L854) is not processing correctly.

_Is it possible that `resolvePath` in [line 22](https://github.com/breck7/scroll/blob/12d21f9120d702c70e31a4566db0542cca175b52/scroll.js#L22), which checks for a forward-slash, may not be working correctly on Windows, which uses a backslash as a directory separator?_

As I said earlier, I am not familiar with JavaScript / TypeScript, so this may be a wild guess on what might be the problem.

### scroll import

Interestingly, the `scroll import` command fails with a completely different error message:

![scroll-import-error](https://user-images.githubusercontent.com/11787866/180332895-8ccd6f78-850d-464c-8117-0e35268e4b88.png)

Since the **scroll.settings** file _does_ exist, then it seems to be either an issue with `resolvePath` or `isScrollFolder` in the [importCommand (lines 831 to 837)](https://github.com/breck7/scroll/blob/12d21f9120d702c70e31a4566db0542cca175b52/scroll.js#L831-L837) -- or so, I'm guessing!

### Summary

It might be possible that since I am using [scoop](https://scoop.sh/) to install Node.Js, that there may an underlying issue with how `scroll-cli` is installed on Windows. I'm sure some straightforward way to resolve this issue can be found. If you need me to do some testing, I would be glad to assist.

Kind Regards,
Liam

**Comment by breck7** [comment]
Thanks for the report! I am able to reproduce the bug(s) on a Windows 10 Azure Cloud instance. Investigating...

**Comment by breck7** [comment]
Thanks @celtic-coder ! There were a lot of places where I wasn't properly accounting for Windows file paths.

Version 25.5.1 is now live on NPM and I was able to successfully run Scroll on Windows.

**Comment by celtic-coder** [comment]
Hi Breck (@breck7),

As you mentioned in the **JTree** [GrammarLanguage.ts (line 2214)](https://github.com/breck7/jtree/blob/6813eff6d8200c09480cac76b2d6d8551e3467f4/core/GrammarLanguage.ts#L2214), it  was _"unavoidable tricky code"_. That was a lot of work to implement those changes in all the affected repos! 

I can confirm that I can run **Scroll** properly in Windows without any error. So, the next step is learning my way around the application.

Thanks, again, for sorting out these issues that affected the application on Windows!

Kind Regards,
Liam
