### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by KnowledgeGarden** [breck7/scroll#58]
Not obvious; usually a license file in the repo

**Comment by celtic-coder** [comment]
Please see [Issue 58](https://github.combreck7/pldb/issues/48) [License Missing] in the [PLDB](https://github.com/breck7/pldb/) repo as I'm sure that Breck would view this Scroll repo in the same light.

**Comment by KnowledgeGarden** [comment]
Ok. His sentiment is for public domain.
