### ISSUE TITLE
Videos too wide on group page

### ISSUE THREAD

**Issue by breck7** [breck7/scroll#60]
<img width="1361" alt="Screen Shot 2022-09-25 at 8 07 25 AM" src="https://user-images.githubusercontent.com/74692/192158491-820c7e33-cd72-42e3-9bfd-bdd32f0dd529.png">
<img width="1374" alt="Screen Shot 2022-09-25 at 8 07 15 AM" src="https://user-images.githubusercontent.com/74692/192158493-284c638b-b51e-4d71-a11c-9d8880a0907d.png">

**Comment by mahadwaseem123** [comment]
Hi @breck7 , Will work on its adjustment.

**Comment by breck7** [comment]
Awesome @mahadwaseem123 !

**Comment by mahadwaseem123** [comment]
Hi @breck7 , I have corrected this issue for CancerDB blog. Can you check if its fine?

**Comment by breck7** [comment]
Much better @mahadwaseem123 ! Great job!

**Comment by mahadwaseem123** [comment]
Thank you so much @breck7 . Can you create the same issue in PLDB repo too? As there are multiple videos there too in Blog which are too wide so I can correct those too.

**Comment by breck7** [comment]
will do

**Comment by breck7** [comment]
here you go @mahadwaseem123 https://github.com/breck7/pldb/issues/126
