### ISSUE TITLE
Show generated files in a directory or a directory with its sub directories

### ISSUE THREAD

**Issue by SRS-WRKS** [breck7/scroll#66]
Note: Thanks to Mr Mahad Waseem , for bringing this to attention 
Currently 
`/node_modules/scroll-cli/scroll.js where`

seems to list scroll files in entire home directory (?) on local machine.

it would be nicer if i could list all the files that were built or will be built in a directory or a directory with its sub directories.

Will help in removing possible stale files creeping into repositories.

**Comment by breck7** [comment]
I think this is 2 issues.

Issue one is that `scroll where` was bad and could be much improved. I just address that.

Issue two is that we need some sort of `scroll clean`. I will create a new issue to track that.

Thanks @SRS-WRKS and @mahadwaseem123! Very helpful
