### ISSUE TITLE
Does scrollnotation compile to treenotation ??

### ISSUE THREAD

**Issue by SRS-WRKS** [breck7/scroll#68]
I am just curious, is scroll notation like typescript is to java script ?? 

Or is it a subset of treenaotaion for simpletons like me :)

**Comment by breck7** [comment]
Sort of like what `package.json` is to `json`, `scroll` is to `tree notation`. Tree Notation is the syntax, Scroll is a DSL in that syntax.

**Comment by SRS-WRKS** [comment]
@breck7   I am sorry, is grid notation a DSL of tree notation . None of this is documented.

**Comment by breck7** [comment]
@SRS-WRKS Grid Notation is just a term for a syntax where you don't have parent child relationships. So both Grid Notation and Tree Notation are 2D syntaxes. Tree notation is a (very important and useful) subset of Grid Notation.

**Comment by SRS-WRKS** [comment]
Thank you have a nice day.
