### ISSUE TITLE
Does scroll  support conditionals for compilation

### ISSUE THREAD

**Issue by SRS-WRKS** [breck7/scroll#69]
As far as i am aware jtree works with scroll to create grammar.

Does scroll support conditional compilation (may be even something as simple as preprocess like C) and is there a command to executed if scroll supports conditional compilation (How autoconf or ./;configure generates a make file for local compilation) 

Most of the documentation i read talks about creating a dialect of scroll for implementation before deployment. 

Possible related issue : https://github.com/breck7/jtree/issues/148

**Comment by breck7** [comment]
Good question. I don't believe we have anything like this yet. If we did it would be hacky done in Javascript and not Grammar. Yes, that is a related issue. Thanks for bringing it up and bumping it up in my priority list.
