### ISSUE TITLE
idea: more concise default header theme

### ISSUE THREAD

**Issue by breck7** [breck7/scroll#70]
drop the middle part, and put an svg Home icon in the top left

![IMG_EBEFEC692D2A-1](https://user-images.githubusercontent.com/74692/195474894-05ee55a2-822b-4906-b6fa-5894d3893196.jpeg)

**Comment by SRS-WRKS** [comment]
For which URL ?? I can try to tackle this but i would need to upskill (atleat i can try to help with these kinds of Issues in the future)
