### ISSUE TITLE
Should scroll-cli support compilation of individual scroll files

### ISSUE THREAD

**Issue by SRS-WRKS** [breck7/scroll#72]
currently scroll cli has a build command which compiles all scroll scripts in a directory to html.

But integration with third party build tools could require a compile command where only a single scroll file is explicitly specified for compilation.

should scroll-cli support that ?

**Comment by breck7** [comment]
Great question @SRS-WRKS ! It does support that when used programatically.

Should we update the readme to make that clear?

<img width="876" alt="Screen Shot 2022-10-20 at 7 08 59 AM" src="https://user-images.githubusercontent.com/74692/196971922-7c33e741-ea46-4db0-a2a8-64545f0c1947.png">
