### ISSUE TITLE
Improve test coverage for pldb to scroll notation conversion

### ISSUE THREAD

**Issue by SRS-WRKS** [breck7/scroll#73]
Many issues prop up when converting from pldb to scroll files,

the commits from pldb repository where the issues fail silently is linked here for reference.

Issue 1) Duplicate fields are allowed implicitly ? (https://github.com/breck7/pldb/commit/48a55e5fdba1b4f35b7af54862c8676eda4c28c0#r86890828)

Issue 2) Mime/File types cant be mentioned for values ?? (https://github.com/breck7/pldb/commit/f0253d8a5f66251564f2a10be3b731c7114ba970 )

**Comment by SRS-WRKS** [comment]
Related: https://github.com/breck7/jtree/issues/158

**Comment by breck7** [comment]
Great points! Working on it

**Comment by SRS-WRKS** [comment]
@breck7 : I wish i knew how to work on this issue.

**Comment by SRS-WRKS** [comment]
Related Issue https://github.com/breck7/pldb/issues/243

**Comment by breck7** [comment]
I'm closing this since I think they are more jtree and pldb related

**Comment by SRS-WRKS** [comment]
@breck7 Converting to scroll would give people an easy way to convert a treenotation DSL to html/json. 

I personally feel it would be a good investment of you code grunt efforts to keep this open :)
