### ISSUE TITLE
Let's nail footnotes/endnotes

### ISSUE THREAD

**Issue by breck7** [breck7/scroll#76]
OpenAI has a cool approach on their blog, that's one to study.

**Comment by celtic-coder** [comment]
Hi Breck (@breck7),

Footnotes and endnotes are not an easy issue to handle. There was an animated [discussion](https://github.com/pml-lang/pml-companion/discussions/85) over at the **Practical Markup Language (PML)** repo on this topic.

There were several draft implementations put forward, and the final [agreed implementation](https://github.com/pml-lang/pml-companion/discussions/85#discussioncomment-3784715) (for the moment), included:

- inline footnotes
- block footnotes.

A discussion with lots of food for thought! 😃

Kind Regards,
Liam

**Comment by breck7** [comment]
Work in progress:

```
* Brockton is a city in Massachusetts. It was incorporated in 1854^inc. 
 https://en.wikipedia.org/wiki/Brockton,_Massachusetts Brockton

^inc Incororated as a city in 1881, but as a town in 1821. Wikipedia.
 https://en.wikipedia.org/wiki/Brockton,_Massachusetts Wikipedia

## Footnotes

notes
```

**Comment by breck7** [comment]
If we do a future revision this is a great reference: https://ab1908.github.io/2021/08/24/footnotes-in-web-content.html

**Comment by breck7** [comment]
Earlier issue for reference: 

https://github.com/breck7/scroll/issues/42

**Comment by celtic-coder** [comment]
Good work, Breck (@breck7)! 🙂
