### ISSUE TITLE
Character encoding regression

### ISSUE THREAD

**Issue by breck7** [breck7/scroll#85]
https://github.com/breck7/CancerDB/issues/14

**Comment by necatituran** [comment]
```
importOnly
description Tools for thought.
github https://github.com/breck7/scroll
viewSourceBaseUrl https://github.com/breck7/scroll/blob/main
twitter https://twitter.com/breckyunits
email feedback@scroll.pub
baseUrl https://scroll.pub/

<!-- Specify the character encoding using the meta tag -->
meta charset="iso-8859-1"

metaTags
scrollCssTag
scrollHeader
```

**Comment by breck7** [comment]
@necatituran you fixed it!

**Comment by breck7** [comment]
> I'm completely new into this, so let me check for today and I'll send it to you tomorrow. Thanks for the video and bounty!

Sounds good! Thank you!

**Comment by necatituran** [comment]
> 

here it is :  76d41b687d4e8ccc1987c3bfe7e805dec98025b520fb5bc0d2c65052e3668e25

**Comment by breck7** [comment]
Sent!

https://explorer.mainnet.near.org/transactions/2JXj2bqcMVxrF7SaTvVaY6EB3KPf4ZHdoFXRL2DZJQPW

Thanks again @necatituran ! Great work!

**Comment by necatituran** [comment]
> Sent!
> 
> https://explorer.mainnet.near.org/transactions/2JXj2bqcMVxrF7SaTvVaY6EB3KPf4ZHdoFXRL2DZJQPW
> 
> Thanks again @necatituran ! Great work!

You're very welcome and thanks for the reward. Best wishes on your project!
