### ISSUE TITLE
add quick wiki inline links?

### ISSUE THREAD

**Issue by breck7** [breck7/scroll#91]
In aftertext should we have an inline link ability like Mediawiki's `Take some more [[tea]]` that compiles to `Take some more <a href="tea">tea</a>`

Might be worth it for wiki use cases etc.

**Comment by fractalqualia** [comment]
Sounds good. But should also include the option to add a "_blank" attribute that compiles to " target='_blank' " if the developer wants to guide the reader to the link in a **new tab**. Currently all links for me open in the same tab if not for hitting the middle mouse button.

**Comment by breck7** [comment]
Good idea @fractalqualia . I just added ability to set target on links.

**Comment by breck7** [comment]
I need to clean up the aftertext code a little bit but then this will be really simple:

https://try.scroll.pub/#scroll%0A%20*%20Here%20is%20my%20%25firstPost%25%20page.%0A%20%20wrap%20%25%20a%20href%3D%22foo%22

**Comment by breck7** [comment]
Here's what Obsidian offers: https://help.obsidian.md/Linking+notes+and+files/Internal+links

I created a small branch to play with this further: https://github.com/breck7/scroll/tree/WikiLinks

**Comment by breck7** [comment]
I haven't fell the need for this too much. Going to close for now.
