### ISSUE TITLE
"scroll list | scroll build" don't index the .html file from the *stories* folder in the index.html file.

### ISSUE THREAD

**Issue by fractalqualia** [breck7/scroll#98]
Here is a video explainer: (sorry for the potato quality)
https://www.loom.com/share/f3feb0ca3e3b40d1a9352442fc246674
 

Using the command "scroll list | scroll build" _will_ write the respective .html files in the 'stories' folder. Still, the file is not referenced in the index.html file and consequently doesn't go live. 

Example: **This file is from 2022.** 
https://github.com/breck7/longbeach.pub/blob/main/stories/grandTheftAuto.scroll

Link where it should appear (but doesn't):
https://longbeach.pub/2022/index.html

**Comment by breck7** [comment]
Hi @fractalqualia! Thank you for creating this issue. I've just pushed a new version that I hope should solve it for you. Let me know! Thanks for your patience!

**Comment by fractalqualia** [comment]
Hey, @breck7 
Just checked it out. It definitely works. Thank you for the speedy additions.
